keboola/go-client

- pkg/client/client_test.go
- pkg/client/waitgroup_test.go
Changes:
- Fixed random failing tests.
> Stabilization of tests

- pkg/encryptionapi/api.go
- pkg/encryptionapi/api_test.go
- pkg/jobsqueueapi/api.go
- pkg/jobsqueueapi/api_test.go
- pkg/jobsqueueapi/error.go
- pkg/jobsqueueapi/job.go
- pkg/jobsqueueapi/time.go
API call na vytvoření jobu, detail jobu a loop čekání na dokončení. (V podstatě jen převzato ze `storageapi/job`.)
> Support Jobs Queue API (KAC-154)

- pkg/sandbox/job.go
- pkg/sandbox/sandbox.go
- pkg/sandbox/sandbox_test.go
https://github.com/keboola/keboola-as-code/pull/835#discussion_r979942000
https://github.com/keboola/keboola-as-code/pull/835#issuecomment-1257933489
> Define more globals + fix `Size` param

- pkg/storageapi/bucket.go
- pkg/storageapi/table.go
- pkg/storageapi/table_test.go
https://keboola.atlassian.net/browse/KAC-242
Changes:
- Remove usage of branch from `ListTablesRequest`
> Fix List Tables API Call in Go Client

- pkg/client/client.go
- pkg/client/client_test.go
Slack: https://keboola.slack.com/archives/C02JAQXLY92/p1664275449058829
> Fix detection of json content type

- pkg/storageapi/bucket.go
- pkg/storageapi/bucket_test.go
- pkg/storageapi/clean.go
- pkg/storageapi/table_test.go
https://keboola.atlassian.net/browse/KAC-252
> Create, list and delete buckets + cleanup Storage within CleanProjectRequest()

- pkg/client/client.go
- pkg/client/request.go
- pkg/storageapi/api.go
- pkg/storageapi/bucket.go
- pkg/storageapi/table.go
- pkg/storageapi/table_test.go
https://keboola.atlassian.net/browse/KAC-261
> Create and delete Storage table

- pkg/platform/clean.go
- pkg/sandboxesapi/instance.go
- pkg/sandboxesapi/sandbox.go
https://github.com/keboola/keboola-as-code/pull/900#issuecomment-1282169981
> Fix deadlocks caused by error channels

- pkg/jobsqueueapi/api.go
- pkg/storageapi/job.go
Related to: https://keboola.atlassian.net/browse/KAC-251
> Add job ID to the error msg

- pkg/client/client.go
- pkg/client/content_type.go
- pkg/client/content_type_test.go
- pkg/jobsqueueapi/api_test.go
Slack: https://keboola.slack.com/archives/C02JAQXLY92/p1666777855523619?thread_ts=1666768368.527989&cid=C02JAQXLY92
> Better detection of the JSON content type

- pkg/storageapi/token.go
- pkg/storageapi/token_test.go
related to https://keboola.atlassian.net/browse/SRE-4038
Tato uprava parsuje description z response VerifyToken storage api requestu. Ak je to master tak sa tam nachadza email uzivatela ktory prave potrebujem.
> storageapi - parse token description

- pkg/jobsqueueapi/api.go
- pkg/storageapi/branch.go
- pkg/storageapi/file.go
- pkg/storageapi/job.go
- pkg/storageapi/job_test.go
- pkg/storageapi/table.go
- pkg/storageapi/table_test.go
https://keboola.atlassian.net/browse/BA-28
https://keboola.atlassian.net/browse/BA-29
> Create table and load data from file

- go.mod
- go.sum
- pkg/storageapi/file.go
- pkg/storageapi/gcs/file.go
- pkg/storageapi/gcs/file_test.go
- pkg/storageapi/testdata/testdata.go
https://keboola.atlassian.net/browse/BA-27
> Support GCS for file upload

- pkg/storageapi/table.go
- pkg/storageapi/table_test.go
https://keboola.atlassian.net/browse/BA-81
> Create table 

- pkg/client/request.go
- pkg/client/request_test.go
- pkg/storageapi/token.go
- pkg/storageapi/token_test.go
https://keboola.atlassian.net/browse/BA-54
> Generate token

- pkg/storageapi/abs/file.go
- pkg/storageapi/abs/file_test.go
- pkg/storageapi/file.go
- pkg/storageapi/gcs/file.go
- pkg/storageapi/gcs/file_test.go
- pkg/storageapi/s3/file.go
- pkg/storageapi/s3/file_test.go
VIz. https://github.com/keboola/keboola-as-code/pull/1043#discussion_r1040574190
> Store upload params in file as pointers

- pkg/storageapi/component.go
- pkg/storageapi/component_test.go
https://keboola.atlassian.net/browse/PSGO-24
> Add component check for `genericCodeBlocksUI` flag

- pkg/storageapi/bucket.go
- pkg/storageapi/bucket_test.go
- pkg/storageapi/bucketid.go
- pkg/storageapi/bucketid_test.go
- pkg/storageapi/hack_test.go
- pkg/storageapi/table.go
- pkg/storageapi/table_test.go
- pkg/storageapi/tableid.go
- pkg/storageapi/tableid_test.go
- pkg/storageapi/token.go
- pkg/storageapi/token_test.go
Part of: https://keboola.atlassian.net/browse/BA-40
Changes:
- Better model for BucketID and TableID.
- Added fuctions `ParseBucketID`, `ParseTableID`.
- Added JSON marshal/unmarshal support.
> Better model for BucketID and TableID

- pkg/storageapi/table.go
- pkg/storageapi/table_test.go
Part of: https://keboola.atlassian.net/browse/BA-42
Changes: 
- Created table is returned from the `CreateTable` function.
> Return created table

- pkg/storageapi/token.go
- pkg/storageapi/token_test.go
Part of: https://keboola.atlassian.net/browse/BA-40
> Add missing method BucketPermissions.MarshalJSON

- pkg/storageapi/file.go
- pkg/storageapi/table.go
- pkg/storageapi/table_test.go
Part of: https://keboola.atlassian.net/browse/BA-40
> Revert deprecated create table API call, it is faster

- pkg/storageapi/table.go
Changes:
- Added missing `WithOnError(ignoreResourceAlreadyExistsError(...))` to the create table op.
> Ignore table already exists error

- .github/workflows/push.yml
- pkg/storageapi/gcs/file_test.go
> Enable tests on GCS

- pkg/client/request.go
- pkg/keboola/storage_bucket.go
- pkg/keboola/storage_bucket_test.go
- pkg/keboola/storage_bucketid.go
- pkg/keboola/storage_bucketid_test.go
- pkg/keboola/storage_table_test.go
- pkg/keboola/storage_token_test.go
Jira: https://keboola.atlassian.net/browse/PSGO-46
Slack: https://keboola.slack.com/archives/CFVRE56UA/p1674719336459959?thread_ts=1674056172.073899&cid=CFVRE56UA
> "c-" prefix is not required by external buckets

- pkg/keboola/storage_table_preview.go
- pkg/keboola/storage_table_preview_test.go
https://keboola.atlassian.net/browse/BA-112
> Table preview request

- pkg/keboola/storage_file.go
- pkg/keboola/storage_file_test.go
- pkg/keboola/storage_file_upload/testdata/testdata.go
- pkg/keboola/storage_table.go
- pkg/keboola/storage_table_preview_test.go
- pkg/keboola/storage_table_test.go
https://keboola.atlassian.net/browse/BA-113
> Refactor `CreateFileResourceRequest`

- .github/workflows/push.yml
- go.mod
- go.sum
- pkg/keboola/api.go
- pkg/keboola/old_queue.go
- pkg/keboola/old_queue_test.go
- pkg/keboola/queue_job.go
https://keboola.atlassian.net/browse/PSGO-58
> Add support for old job queue

- pkg/keboola/storage_file.go
- pkg/keboola/storage_file_download.go
- pkg/keboola/storage_file_test.go
- pkg/keboola/storage_file_upload.go
- pkg/keboola/storage_file_upload/abs/file.go
- pkg/keboola/storage_file_upload/abs/file_test.go
- pkg/keboola/storage_file_upload/gcs/file.go
- pkg/keboola/storage_file_upload/gcs/file_test.go
- pkg/keboola/storage_file_upload/s3/file.go
- pkg/keboola/storage_file_upload/s3/file_test.go
- pkg/keboola/storage_file_upload/testdata/testdata.go
- pkg/keboola/storage_table.go
- pkg/keboola/test.go
Jira: https://keboola.atlassian.net/browse/PSGO-68
Download support for `s3/abs/gcs`:
> Download support

- pkg/keboola/storage_table_preview.go
- pkg/keboola/storage_table_preview_test.go
https://keboola.atlassian.net/browse/PSGO-92
> Update table preview public API

- pkg/keboola/storage_file.go
- pkg/keboola/storage_file_download.go
- pkg/keboola/storage_file_upload/abs/file.go
- pkg/keboola/storage_file_upload/gcs/file.go
- pkg/keboola/storage_file_upload/s3/file.go
- pkg/keboola/storage_file_upload/testdata/testdata.go
Pro https://keboola.atlassian.net/browse/PSGO-103 - získání file size z blob storage kvůli progressbaru
> Allow getting attributes from staging storage

- pkg/keboola/storage_events.go
Jira: https://keboola.atlassian.net/browse/PSGO-86
Slack: https://keboola.slack.com/archives/C02JAQXLY92/p1677853344346269
> Send event as JSON body, not form data

- pkg/keboola/api.go
Jira: https://keboola.atlassian.net/browse/PSGO-125
Slack: https://keboola.slack.com/archives/C02JAQXLY92/p1678187965593689
> Allow connection via HTTP protocol

- pkg/keboola/storage_project.go
Přidávám sem, abych to pak nemusel konvertovat opakovaně v `keboola-as-code`.
> Add String() method to ProjectID

- pkg/client/client.go
- pkg/request/http_request.go
- pkg/request/http_request_test.go
Part of: https://keboola.atlassian.net/browse/PSGO-216
> Add WithHead, WithPatch methods + add request body error

- pkg/keboola/storage_bucket.go
- pkg/keboola/storage_bucketid.go
- pkg/keboola/storage_bucketid_test.go
Jira: https://keboola.atlassian.net/browse/PSGO-217
Slack: https://keboolaglobal.slack.com/archives/C054DF6DZ1B/p1686064033290039
> Remove bucket c- prefix validation

- pkg/keboola/api.go
- pkg/keboola/api_request.go
- pkg/keboola/api_test.go
Part of: https://keboola.atlassian.net/browse/PSGO-246
Changes:
- Added method `API.WithToken` to easly create a new authorized API instance.
> Add WithToken method

- pkg/keboola/storage_component.go
Part of: https://keboola.atlassian.net/browse/PSGO-249
> Add constants for component IDs

- pkg/keboola/storage_clean.go
- pkg/keboola/storage_file.go
- pkg/keboola/storage_file_test.go
- pkg/keboola/storage_file_upload/testdata/testdata.go
- pkg/keboola/storage_table_create.go
- pkg/keboola/storage_table_load.go
- pkg/keboola/storage_table_preview_test.go
- pkg/keboola/storage_table_test.go
- pkg/keboola/storage_table_unload.go
Jira: https://keboola.atlassian.net/browse/PSGO-267
Changes:
- Added `FileKey` struct.
- Fixed empty `File.BranchID` in some cases.
> Add FileKey

- pkg/keboola/storage_file.go
- pkg/keboola/storage_file_upload/testdata/testdata.go
Part of: https://keboola.atlassian.net/browse/PSGO-286
> Add FileUploadCredentials.CredentialsExpiration() time.Time method

- pkg/keboola/storage_table.go
- pkg/keboola/storage_table_column_base_type.go
- pkg/keboola/storage_table_create.go
- pkg/keboola/storage_table_test.go
JIRA: https://keboola.atlassian.net/browse/PSGO-346
- Added an new api call for creating a table.
> refactor: New create table definition

- pkg/keboola/storage_config_test.go
- pkg/keboola/storage_row_test.go
- pkg/keboola/storage_table_list.go
- pkg/keboola/storage_table_test.go
Jira: https://keboola.atlassian.net/browse/PSGO-353
Changes:
- Fixed empty `BranchID` in `ListTablesRequest` results.
> fix: ListTablesRequest, fix empty BranchID in results

- pkg/keboola/storage_table.go
- pkg/keboola/storage_table_create.go
- pkg/keboola/storage_table_test.go
JIRA: https://keboola.atlassian.net/browse/PSGO-346
Changed:
- updated test for creating table definition
- updated struct Table
> refactor: Update test for create table definition, struct table

- pkg/keboola/storage_table_test.go
JIRA: https://keboola.atlassian.net/browse/PSGO-346
Changed: 
- change data type of column
> fix: Change data type of column

- pkg/keboola/storage_table_test.go
JIRA : https://keboola.atlassian.net/browse/PSGO-369
**Change**: 
- updated storage table tests
> tests: Update storage table tests

- .github/workflows/push.yml
- go.mod
- go.sum
- pkg/keboola/storage_table_test.go
- pkg/keboola/workspaces_test.go
JIRA: https://keboola.atlassian.net/browse/PSGO-375
CHANGED: 
- added missing field to test project `"backend":"snowflake/bigquery"`
- updated `go-utils` version
> feat: Add 'backend' field to test project for E2E tests

- pkg/keboola/storage_table_create.go
- pkg/keboola/storage_table_test.go
JIRA: https://keboola.atlassian.net/browse/PSGO-389
**CHANGED**:
- removed omitempty tag
> fix: Remove omitempty tag from ColumnDefinition struct

- pkg/keboola/storage_token.go
- pkg/keboola/storage_token_test.go
JIRA: https://keboola.atlassian.net/browse/PSGO-487
Changed:
- added fields to get project backend
> feat: add fields to get backend project

- pkg/keboola/storage_table_create.go
- pkg/keboola/storage_table_test.go
Changes:
- Removed duplicate `Name` from the `CreateTableDefinition` request, it is already part of `tableKey.TableID.TableName`.
> fix: Remove duplicate name in create table def req

- pkg/keboola/storage_table_create.go
- pkg/keboola/storage_table_test.go
JIRA: https://keboola.atlassian.net/browse/PSGO-497
Changed:
- column definition as optional
> feat: column definition optional

- pkg/keboola/storage_table_create.go
- pkg/keboola/storage_table_test.go
JIRA: https://keboola.atlassian.net/browse/PSGO-500
> feat: basetype pointer

- pkg/keboola/storage_index.go
JIRA: https://keboola.atlassian.net/browse/PSGO-503
CHANGED:
- added method that converts map to slice
> Add method to convert map to slice

- pkg/keboola/storage_clean.go
Jira: https://keboola.atlassian.net/browse/PSGO-507
CI: https://github.com/keboola/keboola-as-code/actions/runs/8537763937/job/23389911838#step:7:1061
Changes:
- Fixed unstable project cleanup before test, see code comments.
> fix: Handle token not found error, on delete

- pkg/keboola/encryption_utils.go
- pkg/keboola/encryption_utils_test.go
Jira: [PSGO-615](https://keboola.atlassian.net/browse/PSGO-615)
**Changes:**
- added `vault` validation
-----------
Slack: https://keboolaglobal.slack.com/archives/C06RG5D7R8V/p1715064465021989?thread_ts=1715064434.950969&cid=C06RG5D7R8V
[PSGO-615]: https://keboola.atlassian.net/browse/PSGO-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add vault validation

- pkg/keboola/storage_file_upload/s3/file.go
See: https://github.com/keboola/keboola-as-code/pull/1818
**Changes:**
- Improved AWS S3 client setup, `AWS_*` envs are no more loaded.
-----------
> fix: Improve AWS S3 client, don't load AWS ENVs

- pkg/keboola/storage_job.go
Jira: [PSGO-750](https://keboola.atlassian.net/browse/PSGO-750)
**Changes:**
- added const for storage job status
-----------
[PSGO-750]: https://keboola.atlassian.net/browse/PSGO-750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add const for storage job status

- pkg/client/trace/otel/otel_test.go
- pkg/client/tranport_test.go
- pkg/keboola/storage_token.go
Jira: [PSGO-994](https://keboola.atlassian.net/browse/PSGO-994)
**Changes:**
-----------
[PSGO-994]: https://keboola.atlassian.net/browse/PSGO-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Verify token returns a storage provider

- README.md
Jira: XXXXX
**Changes:**
- ...
-----------
> docs: Add HTTP Request usage

- pkg/keboola/storage_component.go
- pkg/keboola/storage_component_test.go
Jira: XXXXX
**Changes:**
- Added `IsTransformationWithBlocks` method to verify transformation components containing code blocks.  
- Enhanced functionality for transformation-related operations.  
-----------
> Add IsTransformationWithBlocks method for code block checks

- .github/workflows/codeql-analysis.yml
- .github/workflows/push.yml
Jira: [PSGO-1036](https://keboola.atlassian.net/browse/PSGO-1036)
**Changes:**
- Updated GitHub Actions workflows to use the latest available versions of actions. 
[PSGO-1036]: https://keboola.atlassian.net/browse/PSGO-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update GitHub Actions for latest action versions

- pkg/keboola/scheduler_api.go
- pkg/keboola/scheduler_api_test.go
- pkg/keboola/scheduler_model.go
**Changes:**
- Add support for scheduler GET
- Add attributes of scheduler from GET request into model
-----------
> feat: Add get schedule request

- pkg/keboola/api_endpoints.go
- pkg/keboola/encryption_api.go
- pkg/keboola/queue_api.go
- pkg/keboola/scheduler_api.go
- pkg/keboola/scheduler_api_test.go
- pkg/keboola/scheduler_model.go
- pkg/keboola/storage_token.go
- pkg/keboola/storage_token_test.go
- pkg/keboola/workspaces_api.go
Jira: [PSGO-1043](https://keboola.atlassian.net/browse/PSGO-1043)
**Changes:**
- added missing endpoints
-----------
[PSGO-1043]: https://keboola.atlassian.net/browse/PSGO-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Implement refresh schedule token functionality and add corresponding test
