keboola/go-client

pkg/storageapi/token.go
pkg/storageapi/token_test.go

V tom PR na CLI ohledně template repository branchí (https://github.com/keboola/keboola-as-code/pull/730/files) je chyba. Nenačítají se tam featury projektu, ale stacku. Skočil jsem Michalovi na špek a nezkontroloval to. 😅 Tak tady (v novým Storage klientovi, kterýho jsme vyhodili do tohoto repa) přidávám parsování projektoých featur, abych potom mohl fixnout ten kód v CLI.

Parse project features from verify token request (KAC-142)

---

pkg/storageapi/config_test.go
pkg/storageapi/events_test.go
pkg/storageapi/row.go
pkg/storageapi/row_test.go

V KBC je takový issue že některý config row mají v `created` timestampu prázdný řetězec kvůli nějakýmu bugu z ledna: https://keboola.slack.com/archives/CFVRE56UA/p1656494164678899 a nemají prostor to fixovat. Do CLI jsme před deseti dny přidali Michalův velký refactoring Storage API klienta (https://github.com/keboola/keboola-as-code/pull/724/files) který ale začal ten timestamp parsovat. Snažil jsem se to fixovat, zkoušel jsem všechno možný i napsat custom unmarshaller na ten `Time` typ i na celý `ConfigRow` a poladit tam ručně když přijde `""` ale bez úspěchu. A potom mě napadlo podívat se jestli se vůbec ten timestamp ve CLI/API používá a voila, nepoužívá.
Když CLI dostane z API klienta `storageapi.ConfigRow` tak si ho převede na vlastní `model.ConfigRow` a tam se ten timestamp …

Remove Created timestamp from ConfigRow (KAC-161)

---

pkg/storageapi/api.go
pkg/storageapi/config.go
pkg/storageapi/config_test.go

Potřebujeme ve CLI začít mazat metadata (kvůli https://keboola.atlassian.net/browse/KAC-164), tak přidávám nejdřív samotný request do Storage klienta.

Delete config metadata request (KAC-164)

---

pkg/sandbox/sandbox.go
pkg/sandbox/sandbox_test.go

https://keboola.atlassian.net/browse/KAC-224
Changes:
- Add `sandbox.Create` and `sandbox.Delete` which combine requests from `sandbox/config.go` and `sandbox/job.go`
- Add `sandbox.GetSandboxId` for retrieval of sandbox id from sandbox config

Create/Delete Sandbox in Go Client - combine config/job requests

---

pkg/jobsqueueapi/api.go
pkg/jobsqueueapi/api_test.go
pkg/sandbox/sandbox_test.go

Mno, s tím `time.After()` co jsi mi ukazoval ráno jsem to nebyl schopnej rozjet. Skončí to na něm vždycky okamžitě při prvním pokusu.
Když tam ale nechám `time.Sleep()` a na začátku cyklu zkontroluju jestli nenastal deadline, tak mi to funguje.

Use timeout context in WaitForJob

---

pkg/storageapi/token.go

Slack: https://keboola.slack.com/archives/CMTBFNLF8/p1664295815837169
Changes:
- Storage API doesn't send `token` field in `token verify` response, if a new security project feature - `hide-decrypted-token
` is enabled, so `token` field must be set manually.

Fix: Storage API does not send token in verify response, set it manually

---

pkg/sandboxesapi/config.go
pkg/sandboxesapi/instance.go
pkg/sandboxesapi/sandbox.go
pkg/sandboxesapi/sandbox_test.go
pkg/storageapi/table_test.go

Changes:
- Add `sandboxesapi.SandboxWithConfig`, which contains the two structures
- Add `sandboxesapi.Get` and `sandboxesapi.List`, which return `SandboxWithConfig`
- Update tests to use the new methods, `GetInstanceRequest`, `GetConfigRequest`, `ListInstanceRequest`, and `ListConfigRequest` are now tested implicitly through the combined methods

Combined get/list of Sandbox configs with instances

---

pkg/storageapi/bucket.go

Bug byl tady https://github.com/keboola/go-client/pull/26/files?w=1#diff-40518db63d11c131127b32256dffa7248d9a102c7c67f86f4e7fb65a3f142d2eR105 - když jsem dělal review, tak jsem is nebyl jistý, jestli je ten builder potřeba dát reassigned, a nebo jestli normálně pracuje s tím receiverem. Díval jsem se na kód a přišlo mi, že je to v pohodě. V pohodě to ale nebylo 😄.

Fix `DeleteBucketRequest(WithForce)`

---

pkg/storageapi/token.go
pkg/storageapi/token_test.go

related to https://keboola.atlassian.net/browse/SRE-4038
Tato uprava parsuje admin cast token response ktoru vrati [VerifyToken request](https://keboola.docs.apiary.io/#reference/tokens-and-permissions/token-verification/token-verification) pre token ktory je master. Pre non-master tokeny tam ta admin cast nie je.
Potrebujem to k tomu aby som zistil id kbc uzivatela ktory sa nachadza prave v tej admin casti (property id). 
Ta admin cast response verifytoken requestu vyzera napr takto:
```
"admin": {
"name": "Tomáš Kačur",
"id": 6,
"features": [],
"isOrganizationMember": true,
"role": "admin"
}
```

storageapi client: parse admin part of the token if present

---

pkg/storageapi/config.go

Changes:
- Disabled parallel config row creation, rows are created sequentially per config.

Turn off parallel config row creation

---

pkg/client/parallel.go
pkg/storageapi/clean.go
pkg/storageapi/token.go
pkg/storageapi/token_test.go

Changes:
- All not master tokens are delete in the `Clean` request.

Delete all not master tokens on cleanup

---

pkg/storageapi/clean.go
pkg/storageapi/file.go
pkg/storageapi/file_test.go
pkg/storageapi/testdata/testdata.go

Changes:
- All files are removed by the `Clean` request.
Blocked: 
- https://keboola.slack.com/archives/CFVRE56UA/p1670359914667519
- Bug: Empty files cannot be deleted from the S3 storage.

Remove all files in the Clean request

---

pkg/keboola/example_test.go
pkg/keboola/storage_bucket.go
pkg/keboola/storage_hack_test.go

Jira: https://keboola.atlassian.net/browse/BA-120
Slack: https://keboola.slack.com/archives/C02JAQXLY92/p1674752861626779
Changes:
- Delete bucket request uses `async=1` to prevent internal error.

Delete buckets with async=1

---

pkg/keboola/queue_api.go
pkg/keboola/queue_api_test.go
pkg/keboola/workspaces_job.go

V queue job API nešlo spustit job s branch/tag, tak jsem to zrefaktoroval, aby to podporovalo celý scope toho requestu.
Protože už v `old_queue.go` máme functional options, tak jsem narazil na konflikty (např. `WithBranchID`), tak jsem zkusil použít místo toho builder pattern. Je to skoro identická věc, a podporuje to všechny naše usage patterns (příklady níž), jenom tam pak není šance na konflikt mezi options různých builderů. Má to trochu lepší discoverability v IDE (aspoň u mě, nevím, jak u vás), protože ty options jsou metody na tom builderu.
Postupné přidávání options:
```go
// before
opts := []keboola.SomeOption{}
if condition() {
opts = append(opts, keboola.WithSomething(...))
}
api.Request(requiredOpts, opts...).Send(ctx)
// after
req := api.NewRequest(requiredOpts)
if condition() …
```

Refactor queue job API

---

pkg/keboola/storage_file.go
pkg/keboola/storage_file_download.go
pkg/keboola/storage_file_upload/abs/file.go
pkg/keboola/storage_file_upload/gcs/file.go
pkg/keboola/storage_file_upload/s3/file.go
pkg/keboola/storage_file_upload/testdata/testdata.go

Part of https://keboola.atlassian.net/browse/PSGO-95
Ve `storage file download` commandu budu s manifestem pracovat a bylo by lepší ho dostat už rozparsovaný. (bude pro https://github.com/keboola/keboola-as-code/pull/1210)

Parse slices names from manifest on download

---

pkg/keboola/storage_job.go

Jira: https://keboola.atlassian.net/browse/PSGO-88
Do JSON sa to serializuje s prazdnymi hodnotami, `omitempty` nejde takto pouzit:

Allow null value for StorageJobError

---

pkg/keboola/storage_table.go
pkg/keboola/storage_table_test.go

Přidány `delimiter`, `enclosure` a `escapedBy` pro request na vytvoření tabulky (https://keboola.docs.apiary.io/#reference/tables/create-or-list-tables/create-new-table-from-csv-file-asynchronously)

Add parameters to create table request

---

pkg/client/trace/otel/otel_test.go
pkg/keboola/api.go
pkg/keboola/old_queue.go
pkg/keboola/queue_api.go
pkg/keboola/storage_job.go
pkg/request/api_request.go

Changes:
- WaitForJob functions: tracer is obtained from `parentSpan`.

WaitForJob: Get Tracer from parentSpan

---

pkg/keboola/storage_table_create.go

Changes:
- Added missing `branchID` to the `CreateTableDefinition` API call.

fix: CreateTableDefinition, add missing branchID

---

pkg/keboola/encryption_error.go
pkg/keboola/queue_error.go
pkg/keboola/scheduler_error.go
pkg/keboola/storage_error.go
pkg/keboola/workspaces_error.go

Change:
- If a definition of an `*Error` struct is incomplete (in a unit test), without `request/response` instances, it will not panic.

fix: Fix panic if an error struct is not initialized

---

pkg/keboola/storage_branch.go
pkg/keboola/storage_bucket.go
pkg/keboola/storage_common.go
pkg/keboola/storage_config.go
pkg/keboola/storage_file.go
pkg/keboola/storage_row.go
pkg/keboola/storage_table_create.go
pkg/keboola/storage_table_load.go
pkg/keboola/storage_token.go

Changes:
- All API requests are using JSON body instead of form data body.
- Historically, all Storage API calls supported only form data.
- Then, support for JSON body has been added.
- Now, the `go-client` is switched.
- Motivation: I need to mock some API calls, and JSON format is easier for mocking.

feat: Replace remaining form body with json body

---

build/ci/golangci.yml
pkg/keboola/api.go
pkg/keboola/storage_config.go
pkg/keboola/storage_config_test.go
pkg/keboola/storage_row.go

**Changes:**
- Support rows update using single configuration update call.
- It is sequential update of each row.
- Add RowSortOrder parameter to reorder rows if needed
-----------

fix: Component rows are possible to update using single call. Add rowSortOrder
